/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.diagnostico;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author felip
 */
public class CadastroSintomas extends javax.swing.JFrame {
 List<String> sintomas = new ArrayList<>();
 List<String> sintomasVerificar = new ArrayList<>();
    /**
     * Creates new form CadastroSintomas
     */
    public CadastroSintomas() {
        initComponents();
        try {
        String sintoma = jTxtSintoma.getText();//String captura sintoma a ser cadastrado
        
        
         Connection conexao = conectarBanco();   
        String sql = "SELECT nome FROM sintomas";       
        PreparedStatement pstmt = conexao.prepareStatement(sql);
        ResultSet rs = pstmt.executeQuery();
        
       
         while (rs.next()) {
    String sintomasBanco = rs.getString("nome");
    String padronizado = sintomasBanco.toLowerCase().replaceAll("\\s", "");
    
    sintomas.add(sintomasBanco);
    sintomasVerificar.add(padronizado); // Adicionando em uma array para usos futuros
    
    System.out.println(padronizado);
}
         pstmt.close();
        conexao.close();
         
        } catch (SQLException ex) {
        Logger.getLogger(TelaEditar.class.getName()).log(Level.SEVERE, null, ex);
        
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtSintoma = new javax.swing.JTextField();
        btnCadastro = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Qual sintoma deseja Cadastrar?");

        jTxtSintoma.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        btnCadastro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCadastro.setText("Cadastrar");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });

        jButton1.setText("voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jTxtSintoma, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(btnCadastro))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(jTxtSintoma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnCadastro)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
         String sintomaCadastrado = jTxtSintoma.getText().trim(); // Captura o sintoma a ser cadastrado e remove espaços nas extremidades
    String cadastradoVerificar = sintomaCadastrado.toLowerCase().replaceAll("\\s", ""); // Padroniza o sintoma

    boolean existente = false;
    
    try {
        Connection conexao = conectarBanco();
        
        // Verifica se o sintoma já existe na lista
        for (String sintoma : sintomasVerificar) {
            if (sintoma.equals(cadastradoVerificar)) {
                System.out.println("Igual já");
                existente = true;
                break;
            }
        }
        
        if (!existente) {
            String sql = "INSERT INTO sintomas (nome) VALUES (?);";       
            PreparedStatement pstmt = conexao.prepareStatement(sql);
            pstmt.setString(1, sintomaCadastrado);
            pstmt.executeUpdate();
            pstmt.close();
            sintomasVerificar.add(cadastradoVerificar); // Atualiza a lista de sintomasVerificar
            JOptionPane.showMessageDialog(null, "Sintoma cadastrado com sucesso");
        } else {
            JOptionPane.showMessageDialog(null, "Este sintoma já está cadastrado", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        
        conexao.close();
    } catch (SQLException ex) {
        Logger.getLogger(TelaEditar.class.getName()).log(Level.SEVERE, null, ex);
    }

    }//GEN-LAST:event_btnCadastroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //volta ao menu
        TelaMenu voltar = new TelaMenu();

        voltar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroSintomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroSintomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroSintomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroSintomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroSintomas().setVisible(true);
            }
        });
    }
   private Connection conectarBanco() throws SQLException {
        String url = "jdbc:mysql://localhost:3306/diagnosticoJava";
        String usuario = "root";
        String senha = "root";
        return DriverManager.getConnection(url,usuario,senha);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTxtSintoma;
    // End of variables declaration//GEN-END:variables
}
