/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.diagnostico;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 05750329011
 */
public class TelaDeletar extends javax.swing.JFrame {

    /**
     * Creates new form TelaDeletar
     */
    public TelaDeletar() {
        initComponents();
         try {

        Connection conexao = conectarBanco();   
        String sql = "SELECT nome FROM doencas";       
        PreparedStatement pstmt = conexao.prepareStatement(sql);
        ResultSet rs = pstmt.executeQuery();
        
        List<String> doencas = new ArrayList<>();
        while (rs.next()) {//pega elemento por elemento da table
            String nomeDoenca = rs.getString("nome");
                cbbx.addItem(nomeDoenca);//Adicionando na comboBox
            System.out.println(nomeDoenca);
        }
         pstmt.close();
        conexao.close();
        
        
    } catch (SQLException ex) {
        Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
    }
         try {

        Connection conexao = conectarBanco();   
        String sql = "SELECT nome FROM sintomas";       
        PreparedStatement pstmt = conexao.prepareStatement(sql);
        ResultSet rs = pstmt.executeQuery();
        
        List<String> sintomas = new ArrayList<>();
        while (rs.next()) {//pega elemento por elemento da table
            String nomeSintoma = rs.getString("nome");
                sintomas.add(nomeSintoma);//Adicionando em uma array para usos futuros
                cbbx1.addItem(nomeSintoma);//Adicionando na comboBox
            
               
        }
         pstmt.close();
        conexao.close();
        
        
    } catch (SQLException ex) {
        Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
    }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbbx = new javax.swing.JComboBox<>();
        cbbx1 = new javax.swing.JComboBox<>();
        btnExcluirDoenca = new javax.swing.JButton();
        btnExcluirSintoma = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbbx.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        cbbx1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        btnExcluirDoenca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExcluirDoenca.setText("Excluir");
        btnExcluirDoenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirDoencaActionPerformed(evt);
            }
        });

        btnExcluirSintoma.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExcluirSintoma.setText("Excluir");
        btnExcluirSintoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirSintomaActionPerformed(evt);
            }
        });

        jButton1.setText("voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbbx1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbbx, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnExcluirDoenca)
                            .addComponent(btnExcluirSintoma))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExcluirDoenca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbbx))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbbx1)
                    .addComponent(btnExcluirSintoma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirDoencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirDoencaActionPerformed
        // TODO add your handling code here:
        int indice = cbbx.getSelectedIndex();
        String doenca = cbbx.getSelectedItem().toString();
        int n = JOptionPane.showConfirmDialog(
            null,
            "Deseja mesmo deletar esta doença e suas informações",
            "Cuidado",
            JOptionPane.YES_NO_OPTION);
        System.out.println(n);
        if(n==0){
            JOptionPane.showMessageDialog(null, "Deletado com sucesso");
             try {
            Connection conexao = conectarBanco();
            
            String sql = "delete from sintomas_doencas where id_doenca = ?;";
            
            PreparedStatement pstmt = conexao.prepareStatement(sql);
            pstmt.setString(1, doenca);
         pstmt.executeUpdate();
            
            
            sql = "delete from doencas where nome = ?;";
           pstmt = conexao.prepareStatement(sql);
            pstmt.setString(1, doenca);
          pstmt.executeUpdate();
          
          
            pstmt.close();
            conexao.close();
            
            cbbx.removeItemAt(indice);
        } catch (SQLException ex) {
            Logger.getLogger(InfoDoencas.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else {
            JOptionPane.showMessageDialog(null, "Delete cancelado com sucesso");
        }
       
    }//GEN-LAST:event_btnExcluirDoencaActionPerformed

    private void btnExcluirSintomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirSintomaActionPerformed
        // TODO add your handling code here:
        int indice = cbbx1.getSelectedIndex();
        String sintoma = cbbx1.getSelectedItem().toString();
        int n = JOptionPane.showConfirmDialog(
            null,
            "Deseja mesmo deletar este sintoma e suas informações",
            "Cuidado",
            JOptionPane.YES_NO_OPTION);
        System.out.println(n);
        if(n==0){
            JOptionPane.showMessageDialog(null, "Deletado com sucesso");
             try {
            Connection conexao = conectarBanco();
            
            String sql = "delete from sintomas_doencas where id_sintoma = ?;";
            
            PreparedStatement pstmt = conexao.prepareStatement(sql);
            pstmt.setString(1, sintoma);
         pstmt.executeUpdate();
            
            
            sql = "delete from sintomas where nome = ?;";
           pstmt = conexao.prepareStatement(sql);
            pstmt.setString(1, sintoma);
          pstmt.executeUpdate();
          
          
            pstmt.close();
            conexao.close();
            
            cbbx1.removeItemAt(indice);
        } catch (SQLException ex) {
            Logger.getLogger(InfoDoencas.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else {
            JOptionPane.showMessageDialog(null, "Delete cancelado com sucesso");
        }
    }//GEN-LAST:event_btnExcluirSintomaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //volta ao menu
        TelaMenu voltar = new TelaMenu();

        voltar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeletar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeletar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeletar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeletar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeletar().setVisible(true);
            }
        });
    }
private Connection conectarBanco() throws SQLException {
        String url = "jdbc:mysql://localhost:3306/diagnosticoJava";
        String usuario = "root";
        String senha = "root";
        return DriverManager.getConnection(url,usuario,senha);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluirDoenca;
    private javax.swing.JButton btnExcluirSintoma;
    private javax.swing.JComboBox<String> cbbx;
    private javax.swing.JComboBox<String> cbbx1;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
